name = "CliqueInstanceReader"
uuid = "c7558bbf-5a9d-4d3f-acc7-029493034fcd"
authors = ["Henrik Foss Jørgensen"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
